version: '3.6'
services:
  timescale:
    build:
      context: ./
      dockerfile: db.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: 'hasura/graphql-engine:v1.1.0'
    ports:
      - '8080:8080'
    depends_on:
      - timescale
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:postgrespassword@timescale:5432/postgres'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - graphql-engine
    environment:
      GRAPHQL_URL: 'http://graphql-engine:8080/v1/graphql'
      GRAPHQL_SECRET: myadminsecretkey
